# Generated by Django 4.2 on 2025-01-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("women", "0002_alter_woman_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="woman",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/%Y/%m/%d/", verbose_name="Фото"),
        ),
    ]
